import type { Dataset, GoldRecipe, Lineage, Mapping, ProfileResponse } from "../types";
import { registerPowerAppsGateway, type PlatformGateway } from "./platformClient";

/**
 * Thin contract implemented with files generated by `power-apps add-data-source`
 * and `power-apps add-flow`. Dataverse owns reads/reviews; the worker connector
 * owns bounded compute only.
 */
export interface DataverseBindings {
  getDataset(datasetKey: string): Promise<Dataset>;
  selectAsset(datasetKey: string, assetKey: string): Promise<Dataset>;
  getProfiles(datasetKey: string, assetKey: string): Promise<ProfileResponse>;
  approveAllRules(datasetKey: string, actor: string): Promise<Record<string, unknown>>;
  reviewRule(datasetKey: string, ruleId: string, decision: string, actor: string): Promise<Record<string, unknown>>;
  getMapping(datasetKey: string, assetKey: string): Promise<Mapping>;
  approveAllMappings(datasetKey: string, actor: string): Promise<Record<string, unknown>>;
  approveLayer(datasetKey: string, layer: string, actor: string): Promise<Record<string, unknown>>;
  listGoldRecipes(datasetKey: string): Promise<GoldRecipe[]>;
  createGoldRecipe(datasetKey: string, sourceAsset: string, actor: string): Promise<GoldRecipe>;
  reviewGoldRecipe(datasetKey: string, recipeId: string, actor: string): Promise<GoldRecipe>;
  getLineage(datasetKey: string): Promise<Lineage>;
}

export interface FlowBindings {
  startIngestion(datasetKey: string, force: boolean): Promise<Record<string, unknown>>;
}

export interface WorkerBindings {
  discover(datasetKey: string): Promise<Record<string, unknown>>;
  profile(datasetKey: string): Promise<ProfileResponse>;
  executeRules(datasetKey: string): Promise<Record<string, unknown>>;
  runSilver(datasetKey: string): Promise<Record<string, unknown>>;
  runGold(datasetKey: string, recipeId: string): Promise<Record<string, unknown>>;
}

export function createPowerPlatformGateway(
  dataverse: DataverseBindings,
  flows: FlowBindings,
  worker: WorkerBindings,
  actor = "power-app-user",
): PlatformGateway {
  return {
    getDataset: (key) => dataverse.getDataset(key),
    startIngestion: (key) => flows.startIngestion(key, false),
    discover: (key) => worker.discover(key),
    profile: (key) => worker.profile(key),
    selectAsset: (key, asset) => dataverse.selectAsset(key, asset),
    getProfiles: (key, asset) => dataverse.getProfiles(key, asset),
    approveAllRules: (key) => dataverse.approveAllRules(key, actor),
    executeRules: (key) => worker.executeRules(key),
    reviewRule: (key, ruleId, decision) => dataverse.reviewRule(key, ruleId, decision, actor),
    getMapping: (key, asset) => dataverse.getMapping(key, asset),
    approveAllMappings: (key) => dataverse.approveAllMappings(key, actor),
    approveLayer: (key, layer) => dataverse.approveLayer(key, layer, actor),
    runSilver: (key) => worker.runSilver(key),
    listGoldRecipes: (key) => dataverse.listGoldRecipes(key),
    createGoldRecipe: (key, asset) => dataverse.createGoldRecipe(key, asset, actor),
    reviewGoldRecipe: (key, recipeId) => dataverse.reviewGoldRecipe(key, recipeId, actor),
    runGold: (key, recipeId) => worker.runGold(key, recipeId),
    getLineage: (key) => dataverse.getLineage(key),
  };
}

export function registerPowerPlatformServices(
  dataverse: DataverseBindings,
  flows: FlowBindings,
  worker: WorkerBindings,
  actor?: string,
): void {
  registerPowerAppsGateway(createPowerPlatformGateway(dataverse, flows, worker, actor));
}
